version: 2.1
workflows:
  version: 2
  build:
    jobs:
      - tests
jobs:
  tests:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - run: npm install
      - run: npm test
